accelerator: gpu
batch_size: 64
check_val_every_n_epoch: 10
ckpt_every_n_epoch: 10
cnn_initial_width: 256
cnn_padding: 1
datamodule: cifar10
devices: 1
dropout_prob: 0.5
lr: 0.01
lr_drop: 0.1
lr_steps: [40, 80, 120, 160, 200, 240]
max_epochs: 1
model: resnet
resnet_small_input: True
mlp_hidden_dim: 2000
mlp_num_layers: 5